/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          colors: {
              "surface": "#1b061a",
              "secondary": "#f5ce53",
              "on-tertiary-fixed": "#320032",
              "tertiary": "#ff9cf4",
              "inverse-on-surface": "#684c64",
              "surface-dim": "#1b061a",
              "on-primary-fixed-variant": "#0d6200",
              "outline-variant": "#5a3f56",
              "on-tertiary-fixed-variant": "#6a006a",
              "error": "#ff6e84",
              "on-tertiary-container": "#5b005b",
              "primary-fixed-dim": "#2be800",
              "on-primary-fixed": "#064200",
              "tertiary-fixed": "#fe83f4",
              "secondary-dim": "#e6c047",
              "on-primary": "#0d6100",
              "on-secondary": "#584500",
              "tertiary-container": "#fe83f4",
              "secondary-fixed-dim": "#e6c047",
              "primary-fixed": "#2ff801",
              "outline": "#8b6c85",
              "inverse-primary": "#106f00",
              "on-primary-container": "#0b5800",
              "on-error": "#490013",
              "surface-container-low": "#220a20",
              "on-surface-variant": "#c3a1bc",
              "inverse-surface": "#fff7f9",
              "error-container": "#a70138",
              "secondary-fixed": "#f5ce53",
              "on-secondary-fixed-variant": "#634e00",
              "error-dim": "#d73357",
              "primary": "#8eff71",
              "surface-container": "#2a1028",
              "background": "#1b061a",
              "surface-container-lowest": "#000000",
              "surface-container-high": "#32152f",
              "surface-container-highest": "#3a1a37",
              "on-background": "#ffdbf6",
              "primary-dim": "#2be800",
              "on-secondary-container": "#fff7ea",
              "surface-variant": "#3a1a37",
              "secondary-container": "#735c00",
              "on-secondary-fixed": "#413200",
              "primary-container": "#2ff801",
              "on-surface": "#ffdbf6",
              "on-tertiary": "#6c006c",
              "surface-tint": "#8eff71",
              "on-error-container": "#ffb2b9",
              "tertiary-fixed-dim": "#ee75e5",
              "surface-bright": "#421f3f",
              "tertiary-dim": "#ee75e5"
          },
          fontFamily: {
              "headline": ["Space Grotesk"],
              "body": ["Manrope"],
              "label": ["Space Grotesk"]
          },
          borderRadius: { "DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "0.75rem" },
      },
  },
  plugins: [],
}
